/*
 * System Name     :Post Dragon 
 * Sub system Name :Batch 
 * Function ID     :PST-DRG-I000083
 * Module          :OR ORDERING
 * Process Outline :Send Weekly Production Order to Plant
 *
 * <Revision History>
 * Date       Name(Company Name)             Description 
 * ---------- ------------------------------ ---------------------
 * 28-01-2016  	  z015895(RNTBCI)               Initial Version
 *
 */
package com.nissangroups.pd.i000083.util;

/**
 * Constant file to keep the queries related to the Interface I000083
 * 
 * @author z015895
 *
 */
public class I000083QueryConstants {

	/**
	 * Instantiates a new I000083 query constants.
	 */
	private I000083QueryConstants() {
		super();
	}

	/** I000083 Constant Extract Base Query String */
	public static final StringBuilder baseQuery = new StringBuilder()
			.append("SELECT ROWNUM,MST_OEI_SPEC.CAR_SRS,MST_OEI_SPEC.PROD_FMY_CD,MST_OEI_SPEC.APPLD_MDL_CD,MST_OEI_SPEC.PCK_CD,MST_OSEI.EXT_CLR_CD,")
			.append("MST_OSEI.INT_CLR_CD,TRN_WKLY_PROD_ORDR.EX_NO,MST_OEI_SPEC.SPEC_DESTN_CD,TRN_WKLY_PROD_ORDR.PROD_MTHD_CD,TRN_WKLY_PROD_ORDR.PLNT_CD,")
			.append("TRN_WKLY_PROD_ORDR.ORDR_TAKE_BASE_MNTH,TRN_WKLY_PROD_ORDR.OCF_REGION_CD,TRN_WKLY_PROD_ORDR.TYRE_MKR_CD,TRN_WKLY_PROD_ORDR.LINE_CLASS,")
			.append("TRN_WKLY_PROD_ORDR.DEALER_LST,TRN_WKLY_PROD_ORDR.OWNR_MNL,TRN_WKLY_PROD_ORDR.WRNTY_BKLT,TRN_WKLY_PROD_ORDR.BDY_PRTCTN_CD,")
			.append("TRN_WKLY_PROD_ORDR.ORDR_QTY,TRN_WKLY_PROD_ORDR.PROD_ORDR_NO,TRN_WKLY_PROD_ORDR.SLS_NOTE_NO,MST_OEI_SPEC.ADTNL_SPEC_CD,")
			.append("MST_OEI_BUYER.BUYER_CD,TRN_WKLY_PROD_ORDR.PROD_DAY_NO,TRN_WKLY_PROD_ORDR.PROD_WK_NO,TRN_WKLY_PROD_ORDR.ORDR_FXD_FLAG FROM ")
			.append("MST_OSEI INNER JOIN TRN_WKLY_PROD_ORDR ON MST_OSEI.OSEI_ID =	TRN_WKLY_PROD_ORDR.OSEI_ID ")
			.append("INNER JOIN MST_OEI_BUYER ON MST_OSEI.OEI_BUYER_ID = MST_OEI_BUYER.OEI_BUYER_ID ")
			.append("INNER JOIN MST_OEI_SPEC ON MST_OEI_BUYER.OEI_SPEC_ID = MST_OEI_SPEC.OEI_SPEC_ID ")
			.append("WHERE TRN_WKLY_PROD_ORDR.POR_CD = ':porCd' AND TRN_WKLY_PROD_ORDR.ORDR_TAKE_BASE_MNTH = ':ordrTakBasMnth' AND ")
			.append("TRN_WKLY_PROD_ORDR.ORDR_TAKE_BASE_WK_NO IN (:ordrTakBasWkNo)")
			.append("ORDER BY TRN_WKLY_PROD_ORDR.PROD_WK_NO ASC,TRN_WKLY_PROD_ORDR.PROD_DAY_NO ASC");

	/**
	 * I000083 Constant Extract condition, Please note the * in a.* returns only
	 * the columns selected in the subquery so it does not return all the
	 * columns in this case.
	 */
	public static final StringBuilder baseQueryWithQrpBy = new StringBuilder()
			.append("select rownum, a.* from (SELECT MST_OEI_SPEC.CAR_SRS ,MST_OEI_SPEC.PROD_FMY_CD ,MST_OEI_SPEC.APPLD_MDL_CD ,MST_OEI_SPEC.PCK_CD ,MST_OSEI.EXT_CLR_CD ,")
			.append("MST_OSEI.INT_CLR_CD ,TRN_WKLY_PROD_ORDR.EX_NO ,MST_OEI_SPEC.SPEC_DESTN_CD ,TRN_WKLY_PROD_ORDR.PROD_MTHD_CD,TRN_WKLY_PROD_ORDR.PLNT_CD,")
			.append("TRN_WKLY_PROD_ORDR.ORDR_TAKE_BASE_MNTH ,TRN_WKLY_PROD_ORDR.OCF_REGION_CD ,TRN_WKLY_PROD_ORDR.TYRE_MKR_CD,TRN_WKLY_PROD_ORDR.LINE_CLASS,")
			.append("TRN_WKLY_PROD_ORDR.DEALER_LST ,TRN_WKLY_PROD_ORDR.OWNR_MNL ,TRN_WKLY_PROD_ORDR.WRNTY_BKLT ,TRN_WKLY_PROD_ORDR.BDY_PRTCTN_CD ,")
			.append("LISTAGG(TRN_WKLY_PROD_ORDR.ORDR_QTY,',') WITHIN GROUP (ORDER BY TRN_WKLY_PROD_ORDR.PROD_WK_NO) as  ORDR_QTY,TRN_WKLY_PROD_ORDR.SLS_NOTE_NO ,MST_OEI_SPEC.ADTNL_SPEC_CD ,MST_OEI_BUYER.BUYER_CD ,")
			.append("LISTAGG(TRN_WKLY_PROD_ORDR.PROD_DAY_NO,',') WITHIN GROUP (ORDER BY TRN_WKLY_PROD_ORDR.PROD_WK_NO) as  PROD_DAY_NO,TRN_WKLY_PROD_ORDR.ORDR_FXD_FLAG ,")
			.append("LISTAGG(TRN_WKLY_PROD_ORDR.PROD_WK_NO,',') WITHIN GROUP (ORDER BY TRN_WKLY_PROD_ORDR.PROD_WK_NO) as  PROD_WK_NO,")
			.append("TRN_WKLY_PROD_ORDR.OSEI_ID, '' AS PROD_ORDR_NO FROM MST_OSEI INNER JOIN TRN_WKLY_PROD_ORDR ON MST_OSEI.OSEI_ID =	TRN_WKLY_PROD_ORDR.OSEI_ID ")
			.append("INNER JOIN MST_OEI_BUYER ON MST_OSEI.OEI_BUYER_ID = MST_OEI_BUYER.OEI_BUYER_ID INNER JOIN MST_OEI_SPEC ON MST_OEI_BUYER.OEI_SPEC_ID = MST_OEI_SPEC.OEI_SPEC_ID ")
			.append("WHERE TRN_WKLY_PROD_ORDR.POR_CD = ':porCd' AND TRN_WKLY_PROD_ORDR.ORDR_TAKE_BASE_MNTH = ':ordrTakBasMnth' AND TRN_WKLY_PROD_ORDR.ORDR_TAKE_BASE_WK_NO IN (:ordrTakBasWkNo) ")
			.append("GROUP BY MST_OEI_SPEC.CAR_SRS ,MST_OEI_SPEC.PROD_FMY_CD ,MST_OEI_SPEC.APPLD_MDL_CD ,MST_OEI_SPEC.PCK_CD ,MST_OSEI.EXT_CLR_CD ,MST_OSEI.INT_CLR_CD ,")
			.append("TRN_WKLY_PROD_ORDR.EX_NO ,MST_OEI_SPEC.SPEC_DESTN_CD ,TRN_WKLY_PROD_ORDR.PROD_MTHD_CD ,TRN_WKLY_PROD_ORDR.ORDR_TAKE_BASE_MNTH ,")
			.append("TRN_WKLY_PROD_ORDR.OCF_REGION_CD ,TRN_WKLY_PROD_ORDR.TYRE_MKR_CD ,TRN_WKLY_PROD_ORDR.DEALER_LST ,TRN_WKLY_PROD_ORDR.OWNR_MNL ,TRN_WKLY_PROD_ORDR.WRNTY_BKLT ,")
			.append("TRN_WKLY_PROD_ORDR.BDY_PRTCTN_CD ,TRN_WKLY_PROD_ORDR.SLS_NOTE_NO ,MST_OEI_SPEC.ADTNL_SPEC_CD ,MST_OEI_BUYER.BUYER_CD ,")
			.append("TRN_WKLY_PROD_ORDR.ORDR_FXD_FLAG ,TRN_WKLY_PROD_ORDR.OSEI_ID,TRN_WKLY_PROD_ORDR.PLNT_CD,TRN_WKLY_PROD_ORDR.LINE_CLASS ")
			.append("ORDER BY TRN_WKLY_PROD_ORDR.OSEI_ID) a");

	/** I000083 Order Take Base Month query */
	public static final StringBuilder ordrTakBasMnthQuery = new StringBuilder()
			.append("SELECT MAX(ORDR_TAKE_BASE_MNTH),ORDR_TAKE_BASE_WK_NO FROM MST_WKLY_ORDR_TAKE_BASE WHERE POR = :porCd AND STAGE_CD = 'WK'	")
			.append("AND STAGE_STTS_CD = 'C' GROUP BY ORDR_TAKE_BASE_WK_NO");

	/** I000083 Production Order Number Flag check query */
	public static final StringBuilder prodNoCheckQuery = new StringBuilder()
			.append("SELECT VAL1 FROM MST_PRMTR WHERE PRMTR_CD = 'PROD_ORDR_NO_REQUIRED' AND KEY1 = ':porCd' ");

}
