--------------------------------------------------------
--  File created - Tuesday-August-25-2015   
--------------------------------------------------------

--  Efected on Both NML and Local 27-08-2015

ALTER TABLE MST_END_ITM_SPEC ADD SQL_ID_BACK_UP NUMBER;

update MST_END_ITM_SPEC set SQL_ID_BACK_UP = SEQ_ID;

ALTER TABLE MST_END_ITM_SPEC DROP CONSTRAINT "MST_END_ITM_SPEC_PK";

alter table MST_END_ITM_SPEC drop column SEQ_ID;

alter table MST_END_ITM_SPEC rename column SQL_ID_BACK_UP to SEQ_ID;


ALTER TABLE MST_END_ITM_SPEC ADD CONSTRAINT "MST_END_ITM_SPEC_PK" PRIMARY KEY ("POR_CD", "PROD_FMY_CD", "PROD_STAGE_CD", 

"GSIS_REGION_GRND", "BUYER_CD", "GSIS_APPLD_MDL_NO", "APPLD_MDL_CD", "PCK_CD", "EXT_CLR_CD", "INT_CLR_CD", "SPEC_DESTN_CD", 

"ADTNL_SPEC_CD", "EIM_SPEC_ADPT_DATE", "EIM_SPEC_ABLSH_DATE", "SEQ_ID");


ALTER TABLE MST_PROD_ORDR_TYPE MODIFY (POR_CD CHAR(1 CHAR));
ALTER TABLE TRN_MNTHLY_PROD_ORDR MODIFY (OSEI_ID CHAR(20 CHAR));
