package com.nissangroups.pd.b000053.util;

public class B000053QueryConstants {
	
	public static final StringBuilder getTriggerInfo = new StringBuilder()
	.append("SELECT WKLY_BATCH_PROCESS_STTS.PROD_PRD_FRM,WKLY_BATCH_PROCESS_STTS.PROD_PRD_TO,WKLY_BATCH_PROCESS_STTS.CAR_SRS,WKLY_BATCH_PROCESS_STTS.BUYER_GRP_CD,WKLY_BATCH_PROCESS_STTS.BATCH_ID,WKLY_BATCH_PROCESS_STTS.SEQ_ID,WKLY_BATCH_PROCESS_STTS.POR_CD  FROM WKLY_BATCH_PROCESS_STTS ")
    .append("WHERE WKLY_BATCH_PROCESS_STTS.POR_CD=:porCd AND WKLY_BATCH_PROCESS_STTS.ORDR_TAKE_BASE_MNTH=:ordrTkBsMnth AND WKLY_BATCH_PROCESS_STTS.ORDR_TAKE_BASE_WK_NO=:ordrTkBsWkno AND TRIM(WKLY_BATCH_PROCESS_STTS.BATCH_ID)=:batchId AND TRIM(WKLY_BATCH_PROCESS_STTS.SEQ_ID)=:seqId");/**P0001 Extraction **/
    
}


